name: homes
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  awesome_circular_chart: ^1.1.0
  cached_network_image: ^3.3.1
  dotted_border: ^2.1.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  get_it: ^7.7.0
  image_picker: ^1.1.2
  lottie: ^3.1.2
  provider: ^6.1.2
  sleek_circular_slider: ^2.0.1
  sliding_up_panel: ^2.0.0+1
  syncfusion_flutter_charts: ^26.2.5+1
  table_calendar: ^3.1.2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
dev_dependencies:
  flutter_lints: ^4.0.0

  flutter_native_splash: ^2.3.1
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_1024.png
  android: true
  ios: true


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/favourite.png
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/images/weather/
    - assets/images/settings/
    - assets/icons/svg/
    - assets/Lottie/
    - assets/icons/menu_icons/
    - assets/images/movies/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: "Noto Sans"
      fonts:
        - asset: "assets/fonts/NotoSans-Bold.ttf"
          style: "normal"
        - asset: "assets/fonts/NotoSans-Regular.ttf"
          style: "normal"
    - family: "Poppins"
      fonts:
        - asset: "assets/fonts/Poppins-700.ttf"
          style: "normal"
          weight: 700
    - family: ABeeZee
      fonts:
        - asset: assets/fonts/ABeeZee-Italic.ttf
          style: italic
        - asset: assets/fonts/ABeeZee-Regular.ttf
          style: normal
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend-ExtraLight.ttf
          weight: 200